create separate class (MessageDialogWithScrollableMessage)
ribram/cubrid-manager pull request #2
Opened 2016-11-23 17:07 UTC by paulgheorghecristian

# Conflicts:
#	com.cubrid.common.ui/src/com/cubrid/common/ui/spi/util/CommonUITool.java

2016-12-06 18:17 UTC, ribram requested changes

2016-12-06 18:17 UTC, ribram commented on com.cubrid.common.ui/src/com/cubrid/common/ui/common/dialog/MessageDialogWithScrollableMessage.java
> +
remove one empty line

2016-12-06 18:17 UTC, ribram commented on com.cubrid.common.ui/src/com/cubrid/common/ui/common/dialog/MessageDialogWithScrollableMessage.java
> +
remove one empty line?

2016-12-06 18:17 UTC, ribram commented on com.cubrid.common.ui/src/com/cubrid/common/ui/common/dialog/MessageDialogWithScrollableMessage.java
> +        GridData data = new GridData(SWT.FILL, SWT.FILL, true, true);
is GridData necessary?

2016-12-06 18:17 UTC, ribram commented on com.cubrid.common.ui/src/com/cubrid/common/ui/spi/util/CommonUITool.java
> +	public static int openMsgBox(Shell sh, int dialogImageType, String title, String informativeMessage, String actualMessage,
I am not sure about the way we handle informative message. please verify that all references of openInformationBox have the same behavior.

2016-12-07 04:36 UTC, paulgheorghecristian commented on com.cubrid.common.ui/src/com/cubrid/common/ui/spi/util/CommonUITool.java
> +	public static int openMsgBox(Shell sh, int dialogImageType, String title, String informativeMessage, String actualMessage,
What do you mean, exactly? If i'm not mistaken, it has the same behaviour as before.

2016-12-07 11:53 UTC, paulgheorghecristian commented on com.cubrid.common.ui/src/com/cubrid/common/ui/common/dialog/MessageDialogWithScrollableMessage.java
> +        GridData data = new GridData(SWT.FILL, SWT.FILL, true, true);
yes. without it, the scrollbar doesn't appear ( you cannot scroll at all).

2016-12-07 14:07 UTC, closed without merging